- name: Install pm2
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
# - name: Start or Reload pm2
#   become: yes
#   become_user: ubuntu
#   shell: pm2 startOrReload ecosystem.config.js
