---
- hosts: webservers
  become: yes

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=86400

  roles:
    - nginx
    - postgres
    - nodejs
